# Generated by Django 5.2.8 on 2025-11-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='city',
        ),
        migrations.AlterModelOptions(
            name='barangay',
            options={},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={},
        ),
        migrations.RenameField(
            model_name='towerpin',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='province',
        ),
        migrations.AddField(
            model_name='towerpin',
            name='barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.barangay'),
        ),
        migrations.AddField(
            model_name='towerpin',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tower_pictures/'),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.tower'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.province')),
            ],
        ),
        migrations.AddField(
            model_name='towerpin',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.city'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.city'),
        ),
        migrations.DeleteModel(
            name='CityMunicipality',
        ),
    ]
