# Generated by Django 5.2.8 on 2025-11-22 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_tower_city_alter_barangay_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerpin',
            name='tower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.tower'),
        ),
    ]
