# Generated by Django 5.2.8 on 2025-11-22 04:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_towerpin_tower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerpin',
            name='picture',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
    ]
