# Generated by Django 5.2.8 on 2025-11-22 09:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_towerpin_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerpin',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='towerpin',
            name='picture1',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
            preserve_default=False,
        ),
    ]
