# Generated by Django 5.2.8 on 2025-11-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_towerpin_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerpin',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Rescheduled', 'Rescheduled'), ('Surveyed', 'Surveyed'), ('On Going Construction', 'On Going Construction'), ('Instrumentation', 'Instrumentation'), ('Completed', 'Completed'), ('Up and Running', 'Up and Running'), ('For Repair', 'For Repair'), ('Up but Standby', 'Up but Standby')], default='Scheduled', max_length=50),
        ),
    ]
