# Generated by Django 5.2.8 on 2025-11-22 23:20

import cloudinary_storage.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_towerpin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerpin',
            name='construction_picture',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towerpin',
            name='construction_picture1',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towerpin',
            name='contruction_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='towerpin',
            name='instrumentation_picture',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towerpin',
            name='instrumentation_picture1',
            field=models.ImageField(default=django.utils.timezone.now, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towerpin',
            name='instrumentation_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='towerpin',
            name='technical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Rescheduled', 'Rescheduled'), ('Surveyed', 'Surveyed'), ('On Going Construction', 'On Going Construction'), ('Instrumentation', 'Instrumentation'), ('Completed', 'Completed'), ('Up and Running', 'Up and Running'), ('For Repair', 'For Repair'), ('Up but Standby', 'Up but Standby')], default='Surveyed', max_length=50),
        ),
    ]
