# Generated by Django 5.2.8 on 2025-11-26 07:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_towerpin_construction_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerpin',
            name='construction_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='construction_picture1',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='instrumentation_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='instrumentation_picture1',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
        migrations.AlterField(
            model_name='towerpin',
            name='picture1',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
    ]
