# Generated by Django 5.2.8 on 2025-11-26 21:54

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_towerpin_construction_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerpin',
            name='electrian_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='towerpin',
            name='electrician_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
        migrations.AddField(
            model_name='towerpin',
            name='electrician_picture1',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='SIMOS/'),
        ),
    ]
