# Generated by Django 5.2.8 on 2025-11-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_towerpin_electrian_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towerpin',
            old_name='electrian_remarks',
            new_name='electrician_remarks',
        ),
    ]
