# Generated by Django 5.2.8 on 2026-01-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_alter_towerpin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerpin',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Rescheduled', 'Rescheduled'), ('Surveyed', 'Surveyed'), ('ToBeSurveyed', 'To Be Surveyed'), ('On Going Construction', 'On Going Construction'), ('Electrified', 'Electrified'), ('Not Electrified', 'Not Electrified'), ('Instrumentation', 'Instrumentation'), ('Completed', 'Completed'), ('Up and Running', 'Up and Running'), ('For Repair', 'For Repair'), ('Up but Standby', 'Up but Standby')], default='ToBeSurveyed', max_length=150),
        ),
    ]
